# Generated by Django 5.2.1 on 2025-06-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfeedback',
            name='comment',
        ),
    ]
