# Generated by Django 5.2.1 on 2025-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_reviewfeedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfeedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
