# Generated by Django 5.2.1 on 2025-06-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_reviewfeedback_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfeedback',
            name='comment',
        ),
    ]
