# Generated by Django 5.2.1 on 2025-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_persons_remove_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='persons_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество человек'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
