# Generated by Django 5.2.1 on 2025-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_persons_info_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения (например, кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вес (число)'),
        ),
    ]
