# Generated by Django 5.2.1 on 2025-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_weight_product_weight_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_value',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
