# Generated by Django 5.2.1 on 2025-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_weight_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото пользователя'),
        ),
    ]
