# Generated by Django 5.2.1 on 2025-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_userprofile_photo_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
