# Generated by Django 5.2.1 on 2025-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_carb',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
