# Generated by Django 5.2.1 on 2025-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_nutrition_product_nutrition_carb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='persons_info',
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Оформление'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_fat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_kcal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Калории (Ккал)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_protein',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_carb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес готового торта'),
        ),
    ]
