# Generated by Django 5.2.1 on 2025-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_persons_info_product_composition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition_carb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition_fat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition_kcal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition_protein',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_life',
        ),
        migrations.AddField(
            model_name='product',
            name='persons_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
