# Generated by Django 5.2.1 on 2025-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Подробная информация'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_carb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_fat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_kcal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Калории (Ккал)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_protein',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Белки'),
        ),
    ]
