# Generated by Django 5.2.1 on 2025-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_composition_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DurationField(blank=True, null=True, verbose_name='Срок годности (в днях)'),
        ),
    ]
