# Generated by Django 5.2.1 on 2025-05-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiration_date',
            new_name='shelf_life',
        ),
    ]
