# Generated by Django 5.2.1 on 2025-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_expiration_date_product_shelf_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf_life',
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Срок годности (в днях)'),
        ),
    ]
