# Generated by Django 5.2.1 on 2025-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_shelf_life_product_shelf_life_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shelf_life_days',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Срок годности (в днях)'),
        ),
    ]
