# Generated by Django 5.2.1 on 2025-06-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
