# Generated by Django 5.2.1 on 2025-06-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
