# Generated by Django 5.2.1 on 2025-06-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
