# Generated by Django 5.2.1 on 2025-06-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
