# Generated by Django 5.2.1 on 2025-06-01 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='base',
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='cream',
            field=models.CharField(blank=True, max_length=100, verbose_name='Крем'),
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='decorations',
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='biscuit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бисквит'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Пожелания'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='decoration',
            field=models.CharField(blank=True, max_length=200, verbose_name='Оформление'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='decoration_custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Другое оформление'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='filling',
            field=models.CharField(blank=True, max_length=100, verbose_name='Начинка'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='photo_example',
            field=models.ImageField(blank=True, null=True, upload_to='custom_cakes/photos/', verbose_name='Фото для примера'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='shape',
            field=models.CharField(blank=True, choices=[('circle', 'Круг'), ('square', 'Квадрат'), ('heart', 'Сердце'), ('rectangle', 'Прямоугольник'), ('oval', 'Овал')], max_length=20, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cakes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='weight',
            field=models.FloatField(choices=[(1, '1 кг'), (1.5, '1.5 кг'), (2, '2 кг'), (3, '3 кг'), (5, '5 кг')], default=1, verbose_name='Вес (кг)'),
        ),
        migrations.DeleteModel(
            name='CakeBase',
        ),
        migrations.DeleteModel(
            name='Cream',
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
    ]
