# Generated by Django 5.2.1 on 2025-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0002_remove_customcakeorder_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='decoration_custom',
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='weight',
            field=models.FloatField(default=1, verbose_name='Вес (кг)'),
        ),
    ]
