# Generated by Django 5.2.1 on 2025-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0003_remove_customcakeorder_decoration_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
