# Generated by Django 5.2.1 on 2025-06-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0004_customcakeorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='shape',
        ),
    ]
