# Generated by Django 5.2.1 on 2025-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0005_remove_customcakeorder_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='shape',
            field=models.CharField(blank=True, choices=[('circle', 'Круг'), ('square', 'Квадрат'), ('heart', 'Сердце'), ('rectangle', 'Прямоугольник'), ('oval', 'Овал')], max_length=20, verbose_name='Форма'),
        ),
    ]
