# Generated by Django 5.2.1 on 2025-06-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0006_customcakeorder_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='shape',
        ),
    ]
