# Generated by Django 5.2.1 on 2025-06-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('custom_cake', '0003_remove_customcakeorder_decoration_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_cake.customcakeorder'),
        ),
    ]
