# Generated by Django 5.2.1 on 2025-06-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_price_alter_cart_user_alter_cartitem_cart'),
        ('custom_cake', '0005_remove_customcakeorder_shape'),
        ('shop', '0025_alter_product_weight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'custom_cake'), ('cart', 'product')},
        ),
    ]
