# Generated by Django 5.2.1 on 2025-06-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pickup_method_alter_order_delivery_cost'),
        ('shop', '0024_category_icon_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
